spring:
  profiles:
    include:
      - business-domain
      - kafka # doodlin.messaging:kafka 라이브러리 내부 설정을 사용하기 위해 필요한 설정

server:
  shutdown: graceful
  port: 8080

kafka:
  default:
    consumer: true # KafkaConsumer 빈 등록 여부, default false
#    auto-start: true # default false

---
spring:
  config:
    activate:
      on-profile: local

kafka:
  default:
    group-id: concept-local

---
spring:
  config:
    activate:
      on-profile: dev

kafka:
  default:
    group-id: concept-dev

---
spring:
  config:
    activate:
      on-profile: stage

kafka:
  default:
    group-id: concept-stage

---
spring:
  config:
    activate:
      on-profile: prod

kafka:
  default:
    group-id: concept-prod
